// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOwEb6tWeoW8CLdOUBp96YgQlC3bRYhlY',
    appId: '1:716499571710:web:7065be203ff4f8e9ad66af',
    messagingSenderId: '716499571710',
    projectId: 'mobileapp-85d9a',
    authDomain: 'mobileapp-85d9a.firebaseapp.com',
    storageBucket: 'mobileapp-85d9a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuLyDrUfLvJLStDauMZnCUFpK5t5YIewY',
    appId: '1:716499571710:android:12d4afbe5727e200ad66af',
    messagingSenderId: '716499571710',
    projectId: 'mobileapp-85d9a',
    storageBucket: 'mobileapp-85d9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNEhEbeMqQYOtFqrGfDWQa6FVJi-tfsIg',
    appId: '1:716499571710:ios:26e9b089d0f1b632ad66af',
    messagingSenderId: '716499571710',
    projectId: 'mobileapp-85d9a',
    storageBucket: 'mobileapp-85d9a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNEhEbeMqQYOtFqrGfDWQa6FVJi-tfsIg',
    appId: '1:716499571710:ios:26e9b089d0f1b632ad66af',
    messagingSenderId: '716499571710',
    projectId: 'mobileapp-85d9a',
    storageBucket: 'mobileapp-85d9a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOwEb6tWeoW8CLdOUBp96YgQlC3bRYhlY',
    appId: '1:716499571710:web:e1523972d96faa89ad66af',
    messagingSenderId: '716499571710',
    projectId: 'mobileapp-85d9a',
    authDomain: 'mobileapp-85d9a.firebaseapp.com',
    storageBucket: 'mobileapp-85d9a.appspot.com',
  );
}
